# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
    rust: "1.70"

python:
  install:
    - method: pip
      path: .