name: Build wheels

on:
    pull_request:
        branches:
            - main
            - dev
    push:
        branches:
            - main
            - dev
        # tags:
        #     - v*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [macos-13, macos-14, ubuntu-latest, windows-latest,]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env:
          CIBW_BEFORE_ALL_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
          CIBW_BEFORE_ALL_WINDOWS: rustup target add i686-pc-windows-msvc
          CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"
        #     CIBW_TEST_REQUIRES: pytest
        #     CIBW_TEST_COMMAND: "pytest {project}/tests"


        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"
    
    #   - name: Install cibuildwheel
    #     run: python -m pip install cibuildwheel==2.19.1

    #   - name: Build wheels
    #     run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
